export const FORMULARIO_PROYECTO="FORMULARIO_PROYECTO";
export const GET_PROJECTS="GET_PROJECTS";
export const ADD_PROJECT="ADD_PROJECT";
export const VALIDATE_FORM="VALIDATE_FORM";
export const CURRENT_PROJECT="CURRENT_PROJECT";
export const DELETE_PROJECT="DELETE_PROJECT;"

export const TASKS_PROJECT="TASKS_PROJECT";
export const ADD_TASK="ADD_TASK";
export const VALIDATE_TASK="VALIDATE_TASK";
export const DELETE_TASK="DELETE_TASK";
export const CURRENT_TASK='CURRENT_TASK';
export const UPDATE_TASK='UPDATE_TASK';
export const TASK_UDP="TASK_UDP";
export const CLEAN_TASK="CLEAN_TASK";

export const VIEW_ALERT='VIEW_ALERT';
export const HIDDEN_ALERT='HIDDEN_ALERT';


export const SUCCESFULL_REGISTER='SUCCESFULL_REGISTER';
export const ERROR_REGISTER='ERROR_REGISTER';
export const GET_USER='GET_USER';
export const SUCCESFULL_LOGIN='SUCCESFULL_LOGIN';
export const ERROR_LOGIN='LOGIN_ERROR';
export const LOGOUT='LOGOUT';
export const ERROR_PROJECT='ERROR_PROJECT';
