export const FORMULARIO_PROYECTO="FORMULARIO_PROYECTO";
export const GET_PROJECTS="GET_PROJECTS";
export const ADD_PROJECT="ADD_PROJECT";
export const VALIDATE_FORM="VALIDATE_FORM";
export const CURRENT_PROJECT="CURRENT_PROJECT";
export const DELETE_PROJECT="DELETE_PROJECT;"